#!/usr/bin/env bash
set -e
killall demo 2>/dev/null || true
killall ruiview 2>/dev/null || true
wayland-scanner client-header $XDGSHELL glcv/src/xdg-shell.h
wayland-scanner public-code $XDGSHELL glcv/src/xdg-shell.c
install -d b
cc -Wall -Os -U_FORTIFY_SOURCE `pkg-config wayland-client xkbcommon wayland-egl egl --cflags --libs` -ldl -I glcv/src glcv/src/wl.c ruiview.c gl.c -o b/ruiview
b/ruiview &
cc -Wall -Og -g -U_FORTIFY_SOURCE -I microui/src -I microui/demo demo.c rui.c microui/src/microui.c -o b/demo
b/demo
